# Generated by Django 6.0.2 on 2026-02-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_boards_options_alter_cards_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('outsider', 'Outsider')], default='member', max_length=22),
        ),
    ]
