# Generated by Django 6.0.3 on 2026-04-16 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_boards_role_boardmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('admin', 'Admin')], max_length=22),
        ),
        migrations.AlterUniqueTogether(
            name='boardmember',
            unique_together={('board', 'user')},
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.boards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
