# Generated by Django 6.0.3 on 2026-04-16 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_boardmember_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='boards',
        ),
        migrations.AddField(
            model_name='activity',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='boards.boards'),
            preserve_default=False,
        ),
    ]
