# Generated by Django 6.0.3 on 2026-04-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_inviteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='inviteuser',
            unique_together={('email', 'board')},
        ),
    ]
