# Generated by Django 6.0.3 on 2026-05-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_alter_inviteuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
