# Generated by Django 6.0.3 on 2026-05-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_cards_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
