# Generated by Django 6.0.2 on 2026-02-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'verbose_name': 'Board'},
        ),
        migrations.AlterModelOptions(
            name='cards',
            options={'ordering': ['-task_status'], 'verbose_name': 'Card'},
        ),
        migrations.AlterModelOptions(
            name='lists',
            options={'verbose_name': 'List'},
        ),
    ]
